language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t menelik7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true menelik7/react-test npm test

after_success:
  - docker build -t menelik7/multi-client ./client
  - docker build -t menelik7/multi-nginx ./nginx
  - docker build -t menelik7/multi-server ./server
  - docker build -t menelik7/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push menelik7/multi-client
  - docker push menelik7/multi-nginx
  - docker push menelik7/multi-server
  - docker push menelik7/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-multi"
  env: "Docker-multi-env"
  bucket_name: "elasticbeanstalk-us-east-1-237483526022"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: "$AWS_SECRET_KEY"
